export enum WebSocketErrorType {
    DUPLICATED_CONNECTION = 'DUPLICATED_CONNECTION',
    CHATROOM_NOT_FOUND = 'CHATROOM_NOT_FOUND',
    UNAUTHORIZED = 'UNAUTHORIZED',
    CHATROOM_ENDED = 'CHATROOM_ENDED',
    USER_EXIT_SUCCESSFULLY = 'USER_EXIT_SUCCESSFULLY'
}